"""add responses

Revision ID: 4b18643d8b3b
Revises: 4c4f8f9db0d1
Create Date: 2026-03-13 17:34:02.413638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b18643d8b3b'
down_revision: Union[str, Sequence[str], None] = '4c4f8f9db0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='response_status_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancys.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('resume_id', 'vacancy_id', name='uq_responses_resume_vacancy')
    )
    op.create_index(op.f('ix_responses_resume_id'), 'responses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_responses_vacancy_id'), 'responses', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_vacancy_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_resume_id'), table_name='responses')
    op.drop_table('responses')
    # ### end Alembic commands ###
