"""add message from employeer

Revision ID: a5a17864972a
Revises: c1a8b7e2d341
Create Date: 2026-03-13 20:54:27.101676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a17864972a'
down_revision: Union[str, Sequence[str], None] = 'c1a8b7e2d341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('employer_comment', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_resumes_about_me_trgm'), table_name='resumes', postgresql_ops={'about_me': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_vacancys_description_trgm'), table_name='vacancys', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'employer_comment')
    # ### end Alembic commands ###
