"""update

Revision ID: 82905c5d9a9c
Revises: 46d304cc4e9c
Create Date: 2026-02-27 18:39:30.484201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82905c5d9a9c'
down_revision: Union[str, Sequence[str], None] = '46d304cc4e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('companys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companys', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companys', 'company_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('companys', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('companys', 'company_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companys', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companys', 'title')
    # ### end Alembic commands ###
