"""add func

Revision ID: d6884fa2373d
Revises: 82905c5d9a9c
Create Date: 2026-02-27 18:49:12.854579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6884fa2373d'
down_revision: Union[str, Sequence[str], None] = '82905c5d9a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # pg_trgm — нужен для similarity / trigram поиска
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
