"""add_search_requests

Revision ID: c4ee6b54a4cb
Revises: d6884fa2373d
Create Date: 2026-03-03 20:55:17.868267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ee6b54a4cb'
down_revision: Union[str, Sequence[str], None] = 'd6884fa2373d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchrequests',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchrequests')
    # ### end Alembic commands ###
