"""fix unique user_uuid

Revision ID: ce26965cbe3b
Revises: c4ee6b54a4cb
Create Date: 2026-03-03 22:59:35.804509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce26965cbe3b'
down_revision: Union[str, Sequence[str], None] = 'c4ee6b54a4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('searchrequests_user_uuid_key'), 'searchrequests', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('searchrequests_user_uuid_key'), 'searchrequests', ['user_uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
