"""add resume

Revision ID: e2edc67ebaae
Revises: ce26965cbe3b
Create Date: 2026-03-11 20:32:44.470420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2edc67ebaae'
down_revision: Union[str, Sequence[str], None] = 'ce26965cbe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('resumeeducations',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('SECONDARY', 'SECONDARY_SPECIAL', 'INCOMPLETE_HIGHER', 'BACHELOR', 'SPECIALIST', 'MASTER', 'POSTGRADUATE', 'DOCTORATE', name='education_level_enum'), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_resumeeducations_resume_id'), 'resumeeducations', ['resume_id'], unique=False)
    op.create_table('resumeexperiences',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_resumeexperiences_resume_id'), 'resumeexperiences', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumeexperiences_resume_id'), table_name='resumeexperiences')
    op.drop_table('resumeexperiences')
    op.drop_index(op.f('ix_resumeeducations_resume_id'), table_name='resumeeducations')
    op.drop_table('resumeeducations')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
