networks:
  vacancy_network:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  admin_data:
  bot_states:
  venv_data:
  esdata:

services:

  redis:
    image: redis:7.2-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${CACHE_ADAPTER_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - vacancy_network

  db:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - vacancy_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - vacancy_network
    depends_on:
      redis:
        condition: service_healthy

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
    networks:
      - vacancy_network

  taskiq_worker:
    image: vacancy_backend:latest
    container_name: taskiq_worker
    command: uv run taskiq worker app.core.broker:broker
    volumes:
      - ./src/app:/src/app:cached  
      - venv_data:/src/.venv   
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - vacancy_network

  taskiq_scheduler:
    image: vacancy_backend:latest
    container_name: taskiq_scheduler
    command: uv run taskiq scheduler app.core.scheduler:scheduler
    volumes:
      - ./src/app:/src/app:cached
      - venv_data:/src/.venv
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - vacancy_network

  taskiq_admin:
    image: ghcr.io/taskiq-python/taskiq-admin:latest
    platform: linux/amd64
    container_name: taskiq_admin
    ports:
      - 3000:3000
    environment:
      - TASKIQ_ADMIN_API_TOKEN=supersecret
    volumes:
      - admin_data:/usr/database/
    depends_on:
      taskiq_worker:
        condition: service_started
      taskiq_scheduler:
        condition: service_started
    restart: always
    networks:
      - vacancy_network

  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434"